module.exports = [
  {
    ID: 'VP-1',
    Name: 'Benny - The Bot',
    PIN: '80807',
    ParentID: 1,
    AvatarID: '5',
    GradeLevelID: '1',
    isDyslexic: 'false',
    Wins: 0,
    Losses: 0,
    Total_Points: 0,
    Email: 'benny@benny.net',
    CharacterName: 'Benny - The Bot',
  },
  {
    ID: 'VP-2',
    Name: 'Roby - The Robot',
    PIN: '80807',
    ParentID: 1,
    AvatarID: '9',
    GradeLevelID: '1',
    isDyslexic: 'false',
    Wins: 0,
    Losses: 0,
    Total_Points: 0,
    Email: 'roby@roby.net',
    CharacterName: 'Roby - The Robot',
  },
  {
    ID: 'VP-3',
    Name: 'Hugo',
    PIN: '80807',
    ParentID: 1,
    AvatarID: '6',
    GradeLevelID: '4',
    isDyslexic: 'true',
    Wins: 0,
    Losses: 0,
    Total_Points: 0,
    Email: 'hugo@hugo.net',
    CharacterName: 'Hugo',
  },
  {
    ID: 'VP-4',
    Name: 'Charlie',
    PIN: '80807',
    ParentID: 1,
    AvatarID: '7',
    GradeLevelID: '5',
    isDyslexic: 'true',
    Wins: 0,
    Losses: 0,
    Total_Points: 0,
    Email: 'charlie@charlie.net',
    CharacterName: 'Charlie',
  },
  {
    ID: 'VP-5',
    Name: 'Boto71',
    PIN: '80807',
    ParentID: 1,
    AvatarID: '2',
    GradeLevelID: '2',
    isDyslexic: 'false',
    Wins: 0,
    Losses: 0,
    Total_Points: 0,
    Email: 'boto71@bot.net',
    CharacterName: 'Boto71',
  },
  {
    ID: 'VP-6',
    Name: 'Woebot',
    PIN: '80807',
    ParentID: 1,
    AvatarID: '7',
    GradeLevelID: '5',
    isDyslexic: 'false',
    Wins: 0,
    Losses: 0,
    Total_Points: 0,
    Email: 'woebot@woebot.net',
    CharacterName: 'Woebot',
  },
  {
    ID: 'VP-7',
    Name: 'Scary Bot',
    PIN: '80807',
    ParentID: 1,
    AvatarID: '4',
    GradeLevelID: '4',
    isDyslexic: 'true',
    Wins: 0,
    Losses: 0,
    Total_Points: 0,
    Email: 'scarybot@scarybot.net',
    CharacterName: 'Scary Bot',
  },
];
